# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=50)),
                ('days', models.SmallIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rule', models.SmallIntegerField(editable=False)),
                ('target_time', models.DateTimeField(verbose_name='Time to trigger rule')),
            ],
        ),
        migrations.CreateModel(
            name='TweetMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpw.Community')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpw.TriggerFrequency')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpw.TriggerRule')),
            ],
        ),
    ]
