# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='schema',
            field=models.CharField(default='.', max_length=150),
        ),
    ]
