# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0002_community_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggerrule',
            name='target_time',
            field=models.DateTimeField(null=True, verbose_name='Time to trigger rule'),
        ),
    ]
