# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0004_auto_20160904_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggerfrequency',
            name='days',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='triggerrule',
            name='rule',
            field=models.SmallIntegerField(),
        ),
    ]
