# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0005_auto_20160905_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('dbname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=100)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('access_token_secret', models.CharField(max_length=100)),
            ],
        ),
    ]
