# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0006_databasesettings_twittersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmsg',
            name='last_checked',
            field=models.DateTimeField(null=True, verbose_name='Last performed'),
        ),
        migrations.AlterField(
            model_name='triggerrule',
            name='rule',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
