# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0007_auto_20160911_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
