# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0008_historydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='tweet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tpw.TweetMsg'),
            preserve_default=False,
        ),
    ]
