# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0009_historydata_tweet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='Time when this message was posted')),
                ('tweet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpw.TweetMsg')),
            ],
        ),
    ]
