# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0011_auto_20160914_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetsQueueMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpw.TweetMsg')),
            ],
        ),
        migrations.AddField(
            model_name='tweetlogentry',
            name='success',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweetlogentry',
            name='message',
            field=models.CharField(max_length=140),
        ),
    ]
