# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0012_auto_20160915_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlogentry',
            name='success',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
