# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0013_auto_20160915_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetlogentry',
            old_name='success',
            new_name='error_message',
        ),
    ]
