# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0014_auto_20160915_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerrule',
            name='target_time',
        ),
    ]
