# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0015_remove_triggerrule_target_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmsg',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='First trigger at this date'),
        ),
    ]
