# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpw', '0016_tweetmsg_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmsg',
            name='passed_start_date',
            field=models.BooleanField(default=True),
        ),
    ]
